import React from 'react';
import DocPage from '../components/DocPage';

const twoFactorContent = (
  <div className="prose dark:prose-invert max-w-none">
    <h2>What is Two-Factor Authentication (2FA)?</h2>
    <p>
      <strong>Two-Factor Authentication (2FA)</strong> is an extra layer of
      security for your account. In addition to your password, you’ll be
      required to provide a second form of verification, such as a code from an
      authenticator app or a text message.
    </p>
    <h3>Why Enable 2FA?</h3>
    <ul>
      <li>Protects your account even if your password is compromised.</li>
      <li>Prevents unauthorized access from unknown devices or locations.</li>
      <li>
        Recommended for all users, especially those with sensitive data or admin
        privileges.
      </li>
    </ul>
    <h3>How to Enable 2FA</h3>
    <ol>
      <li>
        Go to your <strong>Account Settings</strong> &rarr;{' '}
        <strong>Security</strong> tab.
      </li>
      <li>
        Click <strong>Enable Two-Factor Authentication</strong>.
      </li>
      <li>
        Scan the QR code with your authenticator app (e.g., Google
        Authenticator, Authy).
      </li>
      <li>Enter the 6-digit code generated by your app to verify setup.</li>
      <li>Save your backup codes in a safe place.</li>
    </ol>
    <h3>Supported 2FA Methods</h3>
    <ul>
      <li>
        <strong>Authenticator Apps:</strong> Time-based one-time passwords
        (TOTP).
      </li>
      <li>
        <strong>SMS Codes:</strong> Receive a code via text message (if
        enabled).
      </li>
      <li>
        <strong>Backup Codes:</strong> Use if you lose access to your device.
      </li>
    </ul>
    <h3>Troubleshooting</h3>
    <ul>
      <li>
        If you lose access to your 2FA device, use a backup code or contact
        support.
      </li>
      <li>
        Ensure your device’s time is correct for authenticator apps to work
        properly.
      </li>
    </ul>
    <p>
      <strong>Tip:</strong> For maximum security, use an authenticator app
      rather than SMS.
    </p>
  </div>
);

export default function TwoFactorAuthenticationPage() {
  return (
    <DocPage
      title="Two-factor Authentication (2FA)"
      description="Learn how to enable and use two-factor authentication (2FA) for enhanced account security."
    >
      {twoFactorContent}
    </DocPage>
  );
}
